name: CI

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
      - run: go version
      - name: Cache
        uses: actions/cache@v5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  version:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: go version

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: golangci/golangci-lint-action@v2

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: go build ./...

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: go test ./... -v -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.txt
          flags: unittests
